### ISSUE TITLE
Error creating rethinkdb datasource in loopback

### ISSUE THREAD

**Issue by dadagama** [fuwaneko/loopback-connector-rethinkdb#20]
Trying to follow this guide:
https://strongloop.com/strongblog/rethinkdb-connector-loopback-node-js-framework/

after run this:
`slc loopback:datasource`
i got this:

```
$ slc loopback:datasource
? Enter the data-source name: rethinkdb
? Select the connector for rethinkdb: other
? Enter the connector name without the loopback-connector- prefix: rethinkdb
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'package' of undefined
    at module.exports.yeoman.generators.Base.extend.installConnector (/usr/lib/node_modules/strongloop/node_modules/generator-loopback/datasource/index.js:201:24)
    at /usr/lib/node_modules/strongloop/node_modules/yeoman-generator/lib/base.js:430:16
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

this is my package.json file so far:

```
{
  "name": "app",
  "version": "1.0.0",
  "main": "server/server.js",
  "scripts": {
    "start": "node .",
    "pretest": "eslint .",
    "posttest": "nsp check"
  },
  "dependencies": {
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^1.3.0",
    "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.4.0",
    "loopback-connector-rethinkdb": "git+https://github.com/fuwaneko/loopback-connector-rethinkdb.git",
    "loopback-datasource-juggler": "^2.39.0",
    "serve-favicon": "^2.0.1"
  },
  "devDependencies": {
    "eslint": "^2.5.3",
    "nsp": "^2.1.0"
  },
  "repository": {
    "type": "",
    "url": ""
  },
  "license": "UNLICENSED",
  "description": "app"
}
```

**Comment by dadagama** [comment]
i had to install this connector using HTTPS GIT URL because this issue:
https://github.com/fuwaneko/loopback-connector-rethinkdb/issues/21

**Comment by fuwaneko** [comment]
I guess yeoman tries to install package via npm where it's not available yet.
